#!/bin/bash
# script to make a menu of the java class files 
# copied to the container, run on container startup

script="menu.sh"

cp $script $script.bak.$(date +%F)
echo -e "#!/bin/bash\n# autogenerated for a container\n# $(date +%F)\n" > $script
for i in $(ls *.class) ; do 
      stripped=$(echo $i |sed s/\.class//)
      listof="$listof $stripped"
done

echo "echo Select which program you want to run" >> $script
# container does not use a shell that has select
# echo "select prog in $listof" >>$script 
echo 'prog="y"' >> $script
echo 'while [[ $prog != "x" ]]' >> $script
echo "do ">>$script
echo "  echo list: $listof ">> $script 
echo '  echo "which program do you want to run ? (x to exit) "' >>$script
echo '  read prog' >>$script
echo '  if [[ $prog == "x" ]] ; then continue ; fi' >>$script
echo '  java $prog '>>$script
echo "done ">>$script
