# dockerfile for apache + php + redis + php 2019 assignment1
FROM ubuntu
MAINTAINER P Campbell pcampbell.edu@gmail.com

# env var for apt-get otherwise I get the error
# debconf: unable to initialize frontend: Dialog
# debconf: (TERM is not set, so the dialog frontend is not usable.)
# debconf: falling back to frontend: Readline
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -y update 

# install apache2 & allow through firewall
RUN apt-get -y install apache2
# don't need this
# todo check how firewall is set in base images??
#RUN ufw allow in "Apache Full"

# install app
# n.b. better to install git, then clone from a repo
# hmmm, can't do recursive copy ?
#COPY app/   /var/www/html/
COPY app.tgz /var/www/html/ 
RUN cd /var/www/html/ ; tar -xzf app.tgz ; rm app.tgz 

# install php & php cli
#RUN apt-get -y install php libapache2-mod-php php-mysql php-cli
RUN apt-get -y install php libapache2-mod-php php-mysql
RUN apt-get -y install php-cli curl

# needed by predis
RUN apt-get -y install zip unzip

# install composer &  redis
RUN curl -sS https://getcomposer.org/installer|php
RUN ./composer.phar require predis/predis

# train the db
# team3 EC  
#RUN ln -s  /var/www/html/project1_team3 /var/www/html/app
#RUN cd /var/www/html/app; php loader.php 
# team6 JM
#RUN ln -s  /var/www/html/Project1team06 /var/www/html/app
# temporarily off, will shell in to try
# RUN ls -l /var/www/html;ls /var/www/html/app/ ;php  /var/www/html/app/load_model.php 

# show container info 
RUN echo "container info: ";uname -a ; echo /etc/*release

