# PMC 2020-04-02
# run firefox from a container
FROM ubuntu:latest 

LABEL maintainer="P Campbell" email="pcampbell.edu@gmail.com" modified="2020-04-02"

# install firefox
# need the apt-get update, as there is no pkg cache
# can't install by name without the update can install after
RUN apt-get update && apt-get install firefox -y 

# launch
ENTRYPOINT [ "/usr/bin/firefox", "-private", "https://www.facebook.com" ]
# for shelling into the container
# CMD sh
