# this is the skeleton file for deploying your own app to heroku

# who
# when
# what

FROM httpd

# put in some appropriate lables
LABEL

# insert the DocumentRoot for the base image httpd, check the image information
WORKDIR

# one or more to copy over your app zip/tarball
COPY

# one or more to extract the zip/tarball
RUN

#for heroku ONLY leave this as a comment until you are finished local testing
#COPY my-httpd.conf /usr/local/apache2/conf/httpd.conf
